*Fix. bug fixes and performance improvements
AllianceBioversityCIAT/onecgiar_pr pull request #271
Opened 2024-05-14 20:24 UTC by xKeCo

2024-05-14 20:36 UTC, yecksin commented
Yes, that's ok

2024-05-14 20:42 UTC, davinzifc commented
Yes, the husky changes are contemplated to be put into production.

2024-05-15 13:15 UTC, gcmartinezg requested changes
Please address the comments before merging with production

2024-05-15 13:27 UTC, davinzifc commented on onecgiar-pr-server/src/api/ipsr/innovation-pathway/dto/update-innovation-pathway.dto.ts
> +  public scalig_ambition!: unknown;
@JuanGuzman-io, can you please review this case since I am not sure what information is expected in that variable

2024-05-15 13:37 UTC, davinzifc commented on onecgiar-pr-server/src/api/ipsr/innovation-pathway/innovation-pathway.controller.ts
>      @UserToken() User: TokenDto,
Variable name corrected

2024-05-15 13:39 UTC, davinzifc commented on onecgiar-pr-server/src/api/results/result-folders/result-folders.service.ts
These cases will be completely resolved throughout the project when the new rules are implemented in the linter.

2024-05-15 19:52 UTC, yecksin commented on onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/pages/ipsr-contributors/components/ipsr-non-pooled-projects/ipsr-non-pooled-projects.component.ts
> +  //     } catch (error) { console.error(error); }
<img width="1059" alt="image" src="https://github.com/AllianceBioversityCIAT/onecgiar_pr/assets/53352977/d7e98ffb-ab9e-4a40-baff-3fd45b8f89bd">

Yes, it doesn't. I've already deleted that commented code.

2024-05-15 19:56 UTC, yecksin commented on onecgiar-pr-client/src/app/shared/services/pusher.service.ts
> +      const oldDate = new Date('4000-05-31T20:40:34.081Z');
You're right, it's already deleted.

2024-05-15 20:04 UTC, gcmartinezg approved these changes

2024-05-15 20:05 UTC, merged